### PR TITLE
Simplification of crypto attack

### PR DESCRIPTION
**Pull request by neonbunny**
Oracle Forms 10gR2 - 12c (and maybe others?) fall back to plain-text comms when the handshake is corrupted. Accordingly, there is no need to tamper with the client-side .jar file, we just need to corrupt the server response enough to stop the client from setting an encryption key.

This can be confirmed with https://forms-demo.com/

### CODE REVIEW

**Comment by v-p-b** [comment]
Wow, this looks great, thank you!

Can you split this into separate PR's so mitmproxy3 support, code formatting and especially the fallback attack can be separated?

**Comment by neonbunny** [comment]
No - it doesn't look like the GitHub PR GUI will let me cherry pick commits. It just wants to create a single PR for all changes.
However, I purposely separated the code formatting commit from the other commits to make it easier to review the functional changes.

**Comment by v-p-b** [comment]
I think you'll need separate branches to do this, but if this too much PITA I can live with it. 

As this is a rather big commit and I also have some unpushed improvements locally this will take a while to review/merge, but I'm on it, stay tuned!

Edit: ETA sometime in June...

**Comment by v-p-b** [comment]
So I can see you are corrupting the handshake at line 109 by replacing "Mate" with "Matf" but I don't see you disabling the crypto. I don't get how this is supposed to work: if communication falls back to plain text and we still apply RC4 we will obviously get some garbage. 

I'm also testing the applications at forms-demo.com (which is a great thing to have for testing btw) but I could fully load any of the demos so far. Did my version work for you out of the box or was any fiddling needed to make it work with 12c (or the test site in particular)?

**Comment by neonbunny** [comment]
I've double checked, and confirmed that this still works - I used DEMO0002 on IE11 FWIW. I did have a few issues getting it to work (because Oracle Forms is clunky):

- I got into a state where the Forms applications were telling me I already had a login form open and it needed to close, which required a reboot to fix,
- it seems Applets are only supported on IE11 these days.

However, once rebooted it worked fine...

I have [IE11 (w/ Forms Applet version is 12.2.1.3, on Java Plug-in 11.171.2.11 x86) -> Burp (port 8080) -> mitmdump (port 8081) -> the web]. The mitm script's response of `Matf` (or anything other than `Mate`) causes the applet's key exchange to fail, resulting in Burp seeing the plain text traffic between the applet and mitmdump. The mitmdump script takes over the encryption operation (instead of the applet) so the final link (mitmdump to web) is still RC4'ed, and the server isn't aware the encryption is being broken.

**Comment by v-p-b** [comment]
OK, so I think what I missed is that it is the client that falls back to plain text (since only his response is corrupted), but the server still uses RC4. This means that we still need to do the crypto, but we don't need to patch/replace the frmall.jar.

**Comment by neonbunny** [comment]
Exactly :)

**Comment by v-p-b** [comment]
As you can see I implemented your suggested changes in master with options handling and also took this opportunity to update the documentation too (your pull request was fine, it just seemed easier like this with all my local changes and required additions). I wanted to keep the original method optional because I ran into cases where the patched client caused some very interesting functionality at server side - I couldn't figure out the details yet unfortunately...

Anyway, this is a great contribution for the project, thanks again!

**Pull request closed without merging**
